---
resources:
- name: movie-fun
  type: git
  source:
    uri: https://github.com/murtazacg/apps-movie-fun-code
    branch: spring-boot

- name: deploy-movie-fun
  type: cf
  source:
    api: https://api.run.haas-69.pez.pivotal.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: mgoga-pal
    space: sandbox
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: movie-fun
    trigger: true
  - task: package
    file: movie-fun/ci/tasks/package.yml
  - put: deploy-movie-fun
    params:
      manifest: movie-fun/manifest.yml
      path: package-output/movie-fun.war